# orion_base/config/params.yaml

# PS5 controller driver
joy_node:
  ros__parameters:
    device_id: 0            # /dev/input/js0
    deadzone: 0.05          # Ignore small stick drifts
    autorepeat_rate: 50.0   # Force 50 msgs/sec even if holding still (matches STM32 Hz)

# Joystick command parser
joystick_parser_node:
  ros__parameters:
    max_speed: 1.0           # Max speed in m/s or rad/s
    max_roll: 0.349          # ~20 degrees in radians
    max_pitch: 0.436         # ~25 degrees in radians
    max_yaw: 0.524           # ~30 degrees in radians
    max_z_offset: 60.0       # Maximum translation up/down in mm
    boost: 0.5               # Extra speed when R2 held
    tilt_step: 0.01          # Step size per tick for roll/pitch/yaw
    z_offset_step: 1.0       # Step size per tick for z position
    xy_offset_multiplier: 40 # Multiplier for xy position control
    pivot_step: 1.0          # Step size for pivot point in mm

# STM32 UART bridge
stm32_bridge_node:
  ros__parameters:
    serial_port: '/dev/ttyTHS1'
    baud_rate: 460800
    send_rate_hz: 50.0      # Timer frequency for UART writes

# Command Mux
cmd_mux_node:
  ros__parameters:
    send_rate_hz: 50.0
    motion_based_eyes: true
    curious_scale_enabled: true
    curious_scale_max: 1.2

# Roboeyes
roboeyes_node:
  ros__parameters:
    width: 1920
    height: 1080
    eye_w: 420 # 120
    eye_h: 525 # 130
    eye_r: 105 # 30
    eye_spacing: 120 # 50
    fullscreen: true
    fps: 60
    eye_color_r: 0
    eye_color_g: 190
    eye_color_b: 255
    blink_duration: 0.2
    blink_interval_min: 1.0
    blink_interval_max: 4.0
    idle_interval_min: 0.5
    idle_interval_max: 2.5
    gaze_smoothing: 0.15
    max_gaze_x_bound: 0.2
    max_gaze_y_bound: 0.25
    power_transition_speed: 0.2
    power_off_has_line: false
    power_off_line_delay: 1.0